### ISSUE TITLE
Doesn't support Unicode astral characters and emoji

### ISSUE THREAD

**Issue by revelt** [ljharb/faucet#22]
Hi
I'm using faucet to format AVA + TAP output. Both default AVA error reporter and vanilla TAP show emoji in test results fine. However, Faucet doesn't understand emoji and often truncates the end of lines that have emoji, or shows broken symbols if error report consists of only emoji:

<img width="125" alt="screen shot 2016-09-09 at 08 13 10" src="https://cloud.githubusercontent.com/assets/8344688/18379988/2d55e95e-766d-11e6-927f-f93108b77849.png">

By the way, the AVA test in question was:

```
test.only('🦄🦄🦄', t => {
    t.pass();
});
```

**Comment by ljharb** [comment]
Looks like instead of just slicing by code units, we need to count graphemes, and consider the "width" option in terms of "number of graphemes" - which would account for emoji.

**Comment by ljharb** [comment]
Although, on the latest code, I'm not getting the truncation, so maybe this has been resolved?

**Comment by revelt** [comment]
hi Jordan! Thank you for picking this up! It's been six years since I raised this, let me double-check.

**Comment by revelt** [comment]
Yeah, looks fine, thank you, I'm closing.
![Screenshot 2022-09-22 at 22 49 05](https://user-images.githubusercontent.com/8344688/191857668-6afe09ea-48b4-40b4-a33a-bf121ef89da6.png)

Have a great day!
