### ISSUE TITLE
Move from deprecated sprintf library to replacement sprintf-js

### ISSUE THREAD

**Issue by daurnimator** [ljharb/faucet#24]
https://www.npmjs.com/package/sprintf is deprecated.
Move to https://www.npmjs.com/package/sprintf-js instead.

**Comment by KacperMadej** [comment]
+1

**Comment by prantlf** [comment]
Included in the forked [@prantlf/faucet](https://www.npmjs.com/package/@prantlf/faucet), among other changes.

**Comment by ljharb** [comment]
Fixed in #26 and #32.
